### ISSUE TITLE
SQL issue

### ISSUE THREAD

**Issue by SimonXIX** [rbernardy/SobekCM-plugin-resultsViewer-SimileTimeline#1]
Hi Richard,

We've just been reviewing this code for handover to SOAS IT. All looks good apart from:

We found that the file SimileTimeline_SobekCM_Settings-insert_script.sql at line 4 attempts an insert into a database table named SobekCM_Setting: no table exists with that name, however a table named SobekCM_Settings with the correct structure does exist. The same file will also not compile due to an unquoted text value "false", on line 5 being supplied as one of the values. This probably just needs quoting. 

Simon Barron
SOAS

**Comment by rbernardy** [comment]
Simon,

Good catch. My apologies. I've corrected, tested, and committed.

Glad to hear that SOAS is going ahead with it.

Thanks

Richard

**Comment by SimonXIX** [comment]
Great, thanks Richard.

Simon
